name: dt_pagination
description: A Pagination Widget for Flutter.
version: 0.0.1
homepage: https://github.com/neechen/dt_pagination

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
